export const CODE_LENGTH = 8;
export const DEFAULT_BENEFIT_DIRECT = 500;
export const DEFAULT_REWARD_DIRECT = 500;
export const DEFAULT_REQ_MINIMUM_DEPOSIT = 500;
export const DEFAULT_MAX_TOTAL_BENEFITS = 500;
export const DEFAULT_MAX_TOTAL_REWARDS = 100;
