export const CODE_LENGTH = 8;
export const DEFAULT_BENEFIT_DIRECT = 100;
export const DEFAULT_REWARD_DIRECT = 20;
export const DEFAULT_REQ_MINIMUM_DEPOSIT: number = null;
export const DEFAULT_MAX_TOTAL_BENEFITS = 10000;
export const DEFAULT_MAX_TOTAL_REWARDS = 2000;
export const DEFAULT_BENEFIT_DEPOSIT_FACTOR = 5;
export const DEFAULT_REWARD_DEPOSIT_FACTOR = 2;
