version: 0.0
os: linux
files:
    - source: /
      destination: /zignaly-test
      overwrite: true
      file_exists_behavior: OVERWRITE
hooks:
    AfterInstall:
        - location: scripts/after_install.sh
          runas: root
          timeout: 300