version: 0.0
os: linux
files:
    - source: /
      destination: /zignaly/{directory}/deploy
file_exists_behavior: OVERWRITE
hooks:
    BeforeInstall:
        - location: scripts/prepare_release.sh
          timeout: 300
          runas: admin
        - location: scripts/delete_old_release.sh
          timeout: 300
          runas: admin
    AfterInstall:
        - location: scripts/after_install.sh
          runas: admin
          timeout: 1200