version: 0.0
os: linux
files:
    - source: /
    destination: /zignaly/{directory}/deploy
file_exists_behavior: OVERWRITE
hooks:
    AfterInstall:
        - location: scripts/after_install.sh
          runas: admin
          timeout: 1200