export enum RewardType {
  SIGNUP_REWARD = 'SIGNUP_REWARD',
  DEPOSIT_REWARD = 'DEPOSIT_REWARD',
  ALLOCATE_REWARD = 'ALLOCATE_REWARD',
  SUCCESS_FEE_REWARD = 'SUCCESS_FEE_REWARD',
  REBATE_COMMISSION_REWARD = 'REBATE_COMMISSION_REWARD',
}

export enum StatusType {
  Completed = 'Completed',
}
