name: Auto-merge into test

on:
  pull_request_review:
    types: [ submitted ]

jobs:
  merge-to-test:
#    if: ${{ github.event.review.state == 'approved' && github.event.pull_request.head.ref == 'master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.ROBOZIGNALY_PAT }}
      - name: Merge the PR branch to origin/test
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: test
          message: Merging ${{ github.event.pull_request.head.ref }}
          from_branch: ${{ github.event.pull_request.head.ref }}
          github_token: ${{ secrets.ROBOZIGNALY_PAT }}
