name: Auto-merge into the test environment

on:
#  push:
  pull_request:
    types: [opened, reopened, edited]
#    branches:
#      - master
#      - chore/**
#      - fix/**
#      - feat/**

jobs:
  merge-to-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge the PR branch to origin/test
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: test
          message: Merging ${{ github.event.pull_request.head.ref }}
          from_branch: ${{ github.event.pull_request.head.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

