name: Auto-merge into test

on:
  pull_request_review:
    types: [ submitted ]

jobs:
  merge-to-test:
    timeout-minutes: 5
    if: ${{ github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.ROBOZIGNALY_PAT }}
      - name: Get clickup id
        id: clickup
        run: |
            CLICKUP_ID=$(echo "${{ github.event.pull_request.title }}" | grep -oP '(?<=(CU-))[#\da-z]+')
            if [ $CLICKUP_ID ] 
            then 
              echo "clickup_status=#$CLICKUP_ID""[in progress]" >> $GITHUB_OUTPUT 
            fi
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v2
      - run: echo ${{steps.clickup.outputs.clickup_id}}
      - name: Merge the PR branch to origin/test
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: test
          message: Merging ${{ github.event.pull_request.head.ref }} ${{steps.clickup.outputs.clickup_status}}
          from_branch: ${{ github.event.pull_request.head.ref }}
          github_token: ${{ secrets.ROBOZIGNALY_PAT }}

