name: PS2 Staging Backoffice deploy
on:
  push:
    branches:
      - feat/wl-theme-wysiwyg
      - master

jobs:
  deploy:
    name: PS2 Staging Backoffice deploy
    uses: ./.github/workflows/ps2-deploy-backoffice.yml
    secrets: inherit
    with:
      deploy-env: test-backoffice # TODO: rename into staging-backoffice
