name: PS2 Prod Backoffice deploy
on:
  push:
    tags:
      - 'release-ps2-*'

jobs:
  deploy:
    name: PS2 Prod Backoffice deploy
    uses: ./.github/workflows/ps2-deploy-backoffice.yml
    secrets: inherit
    with:
      deploy-env: bo-prod
