name: PS2 Staging deploy
on:
  push:
    branches:
      - chore/messing-with-staging2

jobs:
  deploy:
    name: PS2 Staging deploy
    uses: ./.github/workflows/ps2-deploy.yml
    secrets: inherit
    with:
      deploy-env: staging
