name: PS2 Production deploy
on:
  push:
    #tags:
    #  - 'release-ps2-*'
    branches:
      - feat/wl-server-2-prod

jobs:
  deploy:
    name: PS2 WL Server prod deploy
    uses: ./.github/workflows/ps2-deploy.yml
    secrets: inherit
    with:
      deploy-env: wl-prod
