name: PS2 Staging deploy
on:
  push:
    branches:
      - master
      - feat/wl-server-2

jobs:
  deploy:
    name: PS2 WL Staging deploy
    uses: ./.github/workflows/ps2-deploy.yml
    secrets: inherit
    with:
      deploy-env: wl-staging
