name: PS2 Test deploy
on:
  push:
    branches:
      - feat/split-job-deploy

jobs:
  build:
    name: PS2 Build
    uses: ./.github/workflows/ps2-deploy-wl-build.yml
    secrets: inherit
    with:
      deploy-env: wl-staging
  cdn:
    name: PS2 CDN Deploy
    uses: ./.github/workflows/ps2-deploy-wl-cdn.yml
    needs:
      - build
    secrets: inherit
    with:
      deploy-env: wl-staging
  codedeploy:
    name: PS2 Codedeploy Deploy
    uses: ./.github/workflows/ps2-deploy-wl-codedeploy.yml
    needs:
      - build
    secrets: inherit
    with:
      deploy-env: wl-staging
  codedeploy_qw:
    name: PS2 Codedeploy Deploy 2
    uses: ./.github/workflows/ps2-deploy-wl-codedeploy.yml
    needs:
      - build
    secrets: inherit
    with:
      deploy-env: quantwise-prod
  cache:
    name: PS2 Cache clear
    needs:
      - cdn
      - codedeploy
      - codedeploy_qw
    uses: ./.github/workflows/ps2-deploy-wl-cache-nuke.yml
    secrets: inherit
    with:
      deploy-env: wl-staging
  cache_prod_test:
    name: PS2 Cache clear test to make sure prod clears
    needs:
      - cdn
      - codedeploy
      - codedeploy_qw
    uses: ./.github/workflows/ps2-deploy-wl-cache-nuke.yml
    secrets: inherit
    with:
      deploy-env: wl-prod
  cache_qw:
    name: PS2 Cache clear - QW Server
    needs:
      - cdn
      - codedeploy
      - codedeploy_qw
    uses: ./.github/workflows/ps2-deploy-wl-cache-nuke.yml
    secrets: inherit
    with:
      deploy-env: quantwise-prod
