name: PS2 Staging deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: PS2 QW 4-in-1
    uses: ./.github/workflows/ps2-deploy-wl-4-in-1.yml
    secrets: inherit
    with:
      deploy-env: wl-staging
