name: PS2 WL Cache Nuke
on:
  workflow_call:
    inputs:
      deploy-env:
        required: true
        type: string

jobs:
  invalidate:
    name: PS2 Invalidate Cloudfront nd Cloudflare
    runs-on: ubuntu-latest
    environment: ${{ inputs.deploy-env }}
    steps:
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.AWS_DISTRIBUTION }}
          PATHS: '/'
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      - name: Invalidate Cloudflare
        if: ${{ env.HAS_CLOUDFLARE == 'true' }}
        uses: strrife/cloudflare-chunked-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CF_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CF_TOKEN }}
      - name: Wait because Adrian said so
        if: ${{ env.HAS_CLOUDFLARE == 'true' }}
        run: sleep 180s
        shell: bash
      - name: Invalidate Cloudflare AGAIN because 2 is better than 1
        if: ${{ env.HAS_CLOUDFLARE == 'true' }}
        uses: strrife/cloudflare-chunked-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CF_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CF_TOKEN }}

