name: PS2 Deploy
on:
  workflow_call:
    inputs:
      deploy-env:
        required: true
        type: string

jobs:
  build:
    name: PS2 deploy
    timeout-minutes: 20
    runs-on: ubuntu-latest
    environment: crip
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo "${{ env.WHITELABEL }}"
